//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.BookStorage {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CopiesAvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoverImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PublicationYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublisherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CopiesAvailable {
            get {
                return this.CopiesAvailableField;
            }
            set {
                if ((this.CopiesAvailableField.Equals(value) != true)) {
                    this.CopiesAvailableField = value;
                    this.RaisePropertyChanged("CopiesAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoverImageUrl {
            get {
                return this.CoverImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.CoverImageUrlField, value) != true)) {
                    this.CoverImageUrlField = value;
                    this.RaisePropertyChanged("CoverImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN {
            get {
                return this.ISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.ISBNField, value) != true)) {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PublicationYear {
            get {
                return this.PublicationYearField;
            }
            set {
                if ((this.PublicationYearField.Equals(value) != true)) {
                    this.PublicationYearField = value;
                    this.RaisePropertyChanged("PublicationYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Publisher {
            get {
                return this.PublisherField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherField, value) != true)) {
                    this.PublisherField = value;
                    this.RaisePropertyChanged("Publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InventoryUpdate", Namespace="http://schemas.datacontract.org/2004/07/LibraryManagementSystem.Service_Layer.Boo" +
        "k_Storage_Service")]
    [System.SerializableAttribute()]
    public partial class InventoryUpdate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityChangeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookId {
            get {
                return this.BookIdField;
            }
            set {
                if ((object.ReferenceEquals(this.BookIdField, value) != true)) {
                    this.BookIdField = value;
                    this.RaisePropertyChanged("BookId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuantityChange {
            get {
                return this.QuantityChangeField;
            }
            set {
                if ((this.QuantityChangeField.Equals(value) != true)) {
                    this.QuantityChangeField = value;
                    this.RaisePropertyChanged("QuantityChange");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookStorage.IBookStorage")]
    public interface IBookStorage {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStorage/GetAllBooks", ReplyAction="http://tempuri.org/IBookStorage/GetAllBooksResponse")]
        LibraryManagementSystem.BookStorage.Book[] GetAllBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStorage/GetAllBooks", ReplyAction="http://tempuri.org/IBookStorage/GetAllBooksResponse")]
        System.Threading.Tasks.Task<LibraryManagementSystem.BookStorage.Book[]> GetAllBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStorage/GetBookById", ReplyAction="http://tempuri.org/IBookStorage/GetBookByIdResponse")]
        LibraryManagementSystem.BookStorage.Book GetBookById(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStorage/GetBookById", ReplyAction="http://tempuri.org/IBookStorage/GetBookByIdResponse")]
        System.Threading.Tasks.Task<LibraryManagementSystem.BookStorage.Book> GetBookByIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStorage/AddBook", ReplyAction="http://tempuri.org/IBookStorage/AddBookResponse")]
        LibraryManagementSystem.BookStorage.Book AddBook(LibraryManagementSystem.BookStorage.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStorage/AddBook", ReplyAction="http://tempuri.org/IBookStorage/AddBookResponse")]
        System.Threading.Tasks.Task<LibraryManagementSystem.BookStorage.Book> AddBookAsync(LibraryManagementSystem.BookStorage.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStorage/UpdateBook", ReplyAction="http://tempuri.org/IBookStorage/UpdateBookResponse")]
        LibraryManagementSystem.BookStorage.Book UpdateBook(LibraryManagementSystem.BookStorage.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStorage/UpdateBook", ReplyAction="http://tempuri.org/IBookStorage/UpdateBookResponse")]
        System.Threading.Tasks.Task<LibraryManagementSystem.BookStorage.Book> UpdateBookAsync(LibraryManagementSystem.BookStorage.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStorage/DeleteBook", ReplyAction="http://tempuri.org/IBookStorage/DeleteBookResponse")]
        bool DeleteBook(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStorage/DeleteBook", ReplyAction="http://tempuri.org/IBookStorage/DeleteBookResponse")]
        System.Threading.Tasks.Task<bool> DeleteBookAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStorage/GetBooksByCategory", ReplyAction="http://tempuri.org/IBookStorage/GetBooksByCategoryResponse")]
        LibraryManagementSystem.BookStorage.Book[] GetBooksByCategory(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStorage/GetBooksByCategory", ReplyAction="http://tempuri.org/IBookStorage/GetBooksByCategoryResponse")]
        System.Threading.Tasks.Task<LibraryManagementSystem.BookStorage.Book[]> GetBooksByCategoryAsync(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStorage/UpdateInventory", ReplyAction="http://tempuri.org/IBookStorage/UpdateInventoryResponse")]
        bool UpdateInventory(LibraryManagementSystem.BookStorage.InventoryUpdate update);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStorage/UpdateInventory", ReplyAction="http://tempuri.org/IBookStorage/UpdateInventoryResponse")]
        System.Threading.Tasks.Task<bool> UpdateInventoryAsync(LibraryManagementSystem.BookStorage.InventoryUpdate update);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookStorageChannel : LibraryManagementSystem.BookStorage.IBookStorage, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookStorageClient : System.ServiceModel.ClientBase<LibraryManagementSystem.BookStorage.IBookStorage>, LibraryManagementSystem.BookStorage.IBookStorage {
        
        public BookStorageClient() {
        }
        
        public BookStorageClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookStorageClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookStorageClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookStorageClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LibraryManagementSystem.BookStorage.Book[] GetAllBooks() {
            return base.Channel.GetAllBooks();
        }
        
        public System.Threading.Tasks.Task<LibraryManagementSystem.BookStorage.Book[]> GetAllBooksAsync() {
            return base.Channel.GetAllBooksAsync();
        }
        
        public LibraryManagementSystem.BookStorage.Book GetBookById(string id) {
            return base.Channel.GetBookById(id);
        }
        
        public System.Threading.Tasks.Task<LibraryManagementSystem.BookStorage.Book> GetBookByIdAsync(string id) {
            return base.Channel.GetBookByIdAsync(id);
        }
        
        public LibraryManagementSystem.BookStorage.Book AddBook(LibraryManagementSystem.BookStorage.Book book) {
            return base.Channel.AddBook(book);
        }
        
        public System.Threading.Tasks.Task<LibraryManagementSystem.BookStorage.Book> AddBookAsync(LibraryManagementSystem.BookStorage.Book book) {
            return base.Channel.AddBookAsync(book);
        }
        
        public LibraryManagementSystem.BookStorage.Book UpdateBook(LibraryManagementSystem.BookStorage.Book book) {
            return base.Channel.UpdateBook(book);
        }
        
        public System.Threading.Tasks.Task<LibraryManagementSystem.BookStorage.Book> UpdateBookAsync(LibraryManagementSystem.BookStorage.Book book) {
            return base.Channel.UpdateBookAsync(book);
        }
        
        public bool DeleteBook(string id) {
            return base.Channel.DeleteBook(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteBookAsync(string id) {
            return base.Channel.DeleteBookAsync(id);
        }
        
        public LibraryManagementSystem.BookStorage.Book[] GetBooksByCategory(string category) {
            return base.Channel.GetBooksByCategory(category);
        }
        
        public System.Threading.Tasks.Task<LibraryManagementSystem.BookStorage.Book[]> GetBooksByCategoryAsync(string category) {
            return base.Channel.GetBooksByCategoryAsync(category);
        }
        
        public bool UpdateInventory(LibraryManagementSystem.BookStorage.InventoryUpdate update) {
            return base.Channel.UpdateInventory(update);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateInventoryAsync(LibraryManagementSystem.BookStorage.InventoryUpdate update) {
            return base.Channel.UpdateInventoryAsync(update);
        }
    }
}
