//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.BorrowingServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BorrowRecord", Namespace="http://schemas.datacontract.org/2004/07/LMS.BorrowingService.Models")]
    [System.SerializableAttribute()]
    public partial class BorrowRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BorrowDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsReturnedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ReturnDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookId {
            get {
                return this.BookIdField;
            }
            set {
                if ((object.ReferenceEquals(this.BookIdField, value) != true)) {
                    this.BookIdField = value;
                    this.RaisePropertyChanged("BookId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookTitle {
            get {
                return this.BookTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.BookTitleField, value) != true)) {
                    this.BookTitleField = value;
                    this.RaisePropertyChanged("BookTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BorrowDate {
            get {
                return this.BorrowDateField;
            }
            set {
                if ((this.BorrowDateField.Equals(value) != true)) {
                    this.BorrowDateField = value;
                    this.RaisePropertyChanged("BorrowDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((this.DueDateField.Equals(value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsReturned {
            get {
                return this.IsReturnedField;
            }
            set {
                if ((this.IsReturnedField.Equals(value) != true)) {
                    this.IsReturnedField = value;
                    this.RaisePropertyChanged("IsReturned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReturnDate {
            get {
                return this.ReturnDateField;
            }
            set {
                if ((this.ReturnDateField.Equals(value) != true)) {
                    this.ReturnDateField = value;
                    this.RaisePropertyChanged("ReturnDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BorrowLog", Namespace="http://schemas.datacontract.org/2004/07/LMS.BorrowingService.Models")]
    [System.SerializableAttribute()]
    public partial class BorrowLog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ActionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ActionDate {
            get {
                return this.ActionDateField;
            }
            set {
                if ((this.ActionDateField.Equals(value) != true)) {
                    this.ActionDateField = value;
                    this.RaisePropertyChanged("ActionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionType {
            get {
                return this.ActionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionTypeField, value) != true)) {
                    this.ActionTypeField = value;
                    this.RaisePropertyChanged("ActionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookId {
            get {
                return this.BookIdField;
            }
            set {
                if ((object.ReferenceEquals(this.BookIdField, value) != true)) {
                    this.BookIdField = value;
                    this.RaisePropertyChanged("BookId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookTitle {
            get {
                return this.BookTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.BookTitleField, value) != true)) {
                    this.BookTitleField = value;
                    this.RaisePropertyChanged("BookTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Member", Namespace="http://schemas.datacontract.org/2004/07/LMS.BorrowingService.Models")]
    [System.SerializableAttribute()]
    public partial class Member : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime MembershipDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MembershipDate {
            get {
                return this.MembershipDateField;
            }
            set {
                if ((this.MembershipDateField.Equals(value) != true)) {
                    this.MembershipDateField = value;
                    this.RaisePropertyChanged("MembershipDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BorrowingServiceReference.IBorrowingService")]
    public interface IBorrowingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorrowingService/CheckoutBook", ReplyAction="http://tempuri.org/IBorrowingService/CheckoutBookResponse")]
        LibraryManagementSystem.BorrowingServiceReference.BorrowRecord CheckoutBook(string bookId, string userId, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorrowingService/CheckoutBook", ReplyAction="http://tempuri.org/IBorrowingService/CheckoutBookResponse")]
        System.Threading.Tasks.Task<LibraryManagementSystem.BorrowingServiceReference.BorrowRecord> CheckoutBookAsync(string bookId, string userId, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorrowingService/ReturnBook", ReplyAction="http://tempuri.org/IBorrowingService/ReturnBookResponse")]
        LibraryManagementSystem.BorrowingServiceReference.BorrowRecord ReturnBook(string borrowId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorrowingService/ReturnBook", ReplyAction="http://tempuri.org/IBorrowingService/ReturnBookResponse")]
        System.Threading.Tasks.Task<LibraryManagementSystem.BorrowingServiceReference.BorrowRecord> ReturnBookAsync(string borrowId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorrowingService/GetCurrentBorrowsByUser", ReplyAction="http://tempuri.org/IBorrowingService/GetCurrentBorrowsByUserResponse")]
        LibraryManagementSystem.BorrowingServiceReference.BorrowRecord[] GetCurrentBorrowsByUser(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorrowingService/GetCurrentBorrowsByUser", ReplyAction="http://tempuri.org/IBorrowingService/GetCurrentBorrowsByUserResponse")]
        System.Threading.Tasks.Task<LibraryManagementSystem.BorrowingServiceReference.BorrowRecord[]> GetCurrentBorrowsByUserAsync(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorrowingService/GetBorrowHistory", ReplyAction="http://tempuri.org/IBorrowingService/GetBorrowHistoryResponse")]
        LibraryManagementSystem.BorrowingServiceReference.BorrowRecord[] GetBorrowHistory(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorrowingService/GetBorrowHistory", ReplyAction="http://tempuri.org/IBorrowingService/GetBorrowHistoryResponse")]
        System.Threading.Tasks.Task<LibraryManagementSystem.BorrowingServiceReference.BorrowRecord[]> GetBorrowHistoryAsync(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorrowingService/GetAllLogs", ReplyAction="http://tempuri.org/IBorrowingService/GetAllLogsResponse")]
        LibraryManagementSystem.BorrowingServiceReference.BorrowLog[] GetAllLogs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorrowingService/GetAllLogs", ReplyAction="http://tempuri.org/IBorrowingService/GetAllLogsResponse")]
        System.Threading.Tasks.Task<LibraryManagementSystem.BorrowingServiceReference.BorrowLog[]> GetAllLogsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorrowingService/GetMemberById", ReplyAction="http://tempuri.org/IBorrowingService/GetMemberByIdResponse")]
        LibraryManagementSystem.BorrowingServiceReference.Member GetMemberById(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorrowingService/GetMemberById", ReplyAction="http://tempuri.org/IBorrowingService/GetMemberByIdResponse")]
        System.Threading.Tasks.Task<LibraryManagementSystem.BorrowingServiceReference.Member> GetMemberByIdAsync(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorrowingService/CreateMember", ReplyAction="http://tempuri.org/IBorrowingService/CreateMemberResponse")]
        LibraryManagementSystem.BorrowingServiceReference.Member CreateMember(LibraryManagementSystem.BorrowingServiceReference.Member member);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorrowingService/CreateMember", ReplyAction="http://tempuri.org/IBorrowingService/CreateMemberResponse")]
        System.Threading.Tasks.Task<LibraryManagementSystem.BorrowingServiceReference.Member> CreateMemberAsync(LibraryManagementSystem.BorrowingServiceReference.Member member);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBorrowingServiceChannel : LibraryManagementSystem.BorrowingServiceReference.IBorrowingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BorrowingServiceClient : System.ServiceModel.ClientBase<LibraryManagementSystem.BorrowingServiceReference.IBorrowingService>, LibraryManagementSystem.BorrowingServiceReference.IBorrowingService {
        
        public BorrowingServiceClient() {
        }
        
        public BorrowingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BorrowingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BorrowingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BorrowingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LibraryManagementSystem.BorrowingServiceReference.BorrowRecord CheckoutBook(string bookId, string userId, string userName) {
            return base.Channel.CheckoutBook(bookId, userId, userName);
        }
        
        public System.Threading.Tasks.Task<LibraryManagementSystem.BorrowingServiceReference.BorrowRecord> CheckoutBookAsync(string bookId, string userId, string userName) {
            return base.Channel.CheckoutBookAsync(bookId, userId, userName);
        }
        
        public LibraryManagementSystem.BorrowingServiceReference.BorrowRecord ReturnBook(string borrowId) {
            return base.Channel.ReturnBook(borrowId);
        }
        
        public System.Threading.Tasks.Task<LibraryManagementSystem.BorrowingServiceReference.BorrowRecord> ReturnBookAsync(string borrowId) {
            return base.Channel.ReturnBookAsync(borrowId);
        }
        
        public LibraryManagementSystem.BorrowingServiceReference.BorrowRecord[] GetCurrentBorrowsByUser(string userId) {
            return base.Channel.GetCurrentBorrowsByUser(userId);
        }
        
        public System.Threading.Tasks.Task<LibraryManagementSystem.BorrowingServiceReference.BorrowRecord[]> GetCurrentBorrowsByUserAsync(string userId) {
            return base.Channel.GetCurrentBorrowsByUserAsync(userId);
        }
        
        public LibraryManagementSystem.BorrowingServiceReference.BorrowRecord[] GetBorrowHistory(string userId) {
            return base.Channel.GetBorrowHistory(userId);
        }
        
        public System.Threading.Tasks.Task<LibraryManagementSystem.BorrowingServiceReference.BorrowRecord[]> GetBorrowHistoryAsync(string userId) {
            return base.Channel.GetBorrowHistoryAsync(userId);
        }
        
        public LibraryManagementSystem.BorrowingServiceReference.BorrowLog[] GetAllLogs() {
            return base.Channel.GetAllLogs();
        }
        
        public System.Threading.Tasks.Task<LibraryManagementSystem.BorrowingServiceReference.BorrowLog[]> GetAllLogsAsync() {
            return base.Channel.GetAllLogsAsync();
        }
        
        public LibraryManagementSystem.BorrowingServiceReference.Member GetMemberById(string userId) {
            return base.Channel.GetMemberById(userId);
        }
        
        public System.Threading.Tasks.Task<LibraryManagementSystem.BorrowingServiceReference.Member> GetMemberByIdAsync(string userId) {
            return base.Channel.GetMemberByIdAsync(userId);
        }
        
        public LibraryManagementSystem.BorrowingServiceReference.Member CreateMember(LibraryManagementSystem.BorrowingServiceReference.Member member) {
            return base.Channel.CreateMember(member);
        }
        
        public System.Threading.Tasks.Task<LibraryManagementSystem.BorrowingServiceReference.Member> CreateMemberAsync(LibraryManagementSystem.BorrowingServiceReference.Member member) {
            return base.Channel.CreateMemberAsync(member);
        }
    }
}
