//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.SearchServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SearchServiceReference.ISearchService")]
    public interface ISearchService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/SearchBooks", ReplyAction="http://tempuri.org/ISearchService/SearchBooksResponse")]
        LMS.BookSearch.Models.Book[] SearchBooks(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/SearchBooks", ReplyAction="http://tempuri.org/ISearchService/SearchBooksResponse")]
        System.Threading.Tasks.Task<LMS.BookSearch.Models.Book[]> SearchBooksAsync(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/AdvancedSearch", ReplyAction="http://tempuri.org/ISearchService/AdvancedSearchResponse")]
        LMS.BookSearch.Models.Book[] AdvancedSearch(string title, string author, string category, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/AdvancedSearch", ReplyAction="http://tempuri.org/ISearchService/AdvancedSearchResponse")]
        System.Threading.Tasks.Task<LMS.BookSearch.Models.Book[]> AdvancedSearchAsync(string title, string author, string category, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/GetRecommendations", ReplyAction="http://tempuri.org/ISearchService/GetRecommendationsResponse")]
        LMS.BookSearch.Models.Book[] GetRecommendations(string bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/GetRecommendations", ReplyAction="http://tempuri.org/ISearchService/GetRecommendationsResponse")]
        System.Threading.Tasks.Task<LMS.BookSearch.Models.Book[]> GetRecommendationsAsync(string bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/GetPopularBooks", ReplyAction="http://tempuri.org/ISearchService/GetPopularBooksResponse")]
        LMS.BookSearch.Models.Book[] GetPopularBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/GetPopularBooks", ReplyAction="http://tempuri.org/ISearchService/GetPopularBooksResponse")]
        System.Threading.Tasks.Task<LMS.BookSearch.Models.Book[]> GetPopularBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/GetAllCategories", ReplyAction="http://tempuri.org/ISearchService/GetAllCategoriesResponse")]
        string[] GetAllCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/GetAllCategories", ReplyAction="http://tempuri.org/ISearchService/GetAllCategoriesResponse")]
        System.Threading.Tasks.Task<string[]> GetAllCategoriesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISearchServiceChannel : LibraryManagementSystem.SearchServiceReference.ISearchService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchServiceClient : System.ServiceModel.ClientBase<LibraryManagementSystem.SearchServiceReference.ISearchService>, LibraryManagementSystem.SearchServiceReference.ISearchService {
        
        public SearchServiceClient() {
        }
        
        public SearchServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LMS.BookSearch.Models.Book[] SearchBooks(string query) {
            return base.Channel.SearchBooks(query);
        }
        
        public System.Threading.Tasks.Task<LMS.BookSearch.Models.Book[]> SearchBooksAsync(string query) {
            return base.Channel.SearchBooksAsync(query);
        }
        
        public LMS.BookSearch.Models.Book[] AdvancedSearch(string title, string author, string category, string year) {
            return base.Channel.AdvancedSearch(title, author, category, year);
        }
        
        public System.Threading.Tasks.Task<LMS.BookSearch.Models.Book[]> AdvancedSearchAsync(string title, string author, string category, string year) {
            return base.Channel.AdvancedSearchAsync(title, author, category, year);
        }
        
        public LMS.BookSearch.Models.Book[] GetRecommendations(string bookId) {
            return base.Channel.GetRecommendations(bookId);
        }
        
        public System.Threading.Tasks.Task<LMS.BookSearch.Models.Book[]> GetRecommendationsAsync(string bookId) {
            return base.Channel.GetRecommendationsAsync(bookId);
        }
        
        public LMS.BookSearch.Models.Book[] GetPopularBooks() {
            return base.Channel.GetPopularBooks();
        }
        
        public System.Threading.Tasks.Task<LMS.BookSearch.Models.Book[]> GetPopularBooksAsync() {
            return base.Channel.GetPopularBooksAsync();
        }
        
        public string[] GetAllCategories() {
            return base.Channel.GetAllCategories();
        }
        
        public System.Threading.Tasks.Task<string[]> GetAllCategoriesAsync() {
            return base.Channel.GetAllCategoriesAsync();
        }
    }
}
