using System;
using System.Collections.Generic;
using System.ServiceModel;
using LMS.BorrowingService.Models;
using System.ServiceModel.Description;

namespace LMS.BorrowingService.Services
{
    /// <summary>
    /// Client proxy class for interacting with the BookStorage service
    /// </summary>
    public class BookServiceClient
    {
        private BookServiceReference.BookServiceClient _client;
        private readonly string _endpoint;

        /// <summary>
        /// Constructor that uses the configured endpoint from WCF configuration
        /// </summary>
        public BookServiceClient()
        {
            var binding = new BasicHttpBinding();
            var address = new EndpointAddress("http://localhost:44355/Services/BookService.svc");
            _client = new BookServiceReference.BookServiceClient(binding, address);
        }

        /// <summary>
        /// Constructor that uses a specified endpoint URL
        /// </summary>
        /// <param name="endpoint">The service endpoint URL</param>
        public BookServiceClient(string endpoint)
        {
            _endpoint = endpoint;
            var binding = new BasicHttpBinding();
            var address = new EndpointAddress(endpoint);
            _client = new BookServiceReference.BookServiceClient(binding, address);
        }

        /// <summary>
        /// Gets a book by its ID
        /// </summary>
        /// <param name="id">The book ID to retrieve</param>
        /// <returns>The book if found, null otherwise</returns>
        public Book GetBookById(string id)
        {
            try
            {
                var book = _client.GetBookById(id);
                if (book == null)
                {
                    throw new InvalidOperationException($"Book with ID {id} not found");
                }
                
                return ConvertToLocalBookModel(book);
            }
            catch (EndpointNotFoundException ex)
            {
                throw new ServiceException("Book service is not available", ex);
            }
            catch (Exception ex)
            {
                throw new ServiceException($"Error getting book by ID: {ex.Message}", ex);
            }
        }

        /// <summary>
        /// Updates the inventory for a book
        /// </summary>
        /// <param name="update">The inventory update containing the book ID and quantity change</param>
        /// <returns>True if successful, false otherwise</returns>
        public bool UpdateInventory(InventoryUpdate update)
        {
            try
            {
                var serviceUpdate = new BookServiceReference.InventoryUpdate
                {
                    BookId = update.BookId,
                    QuantityChange = update.QuantityChange
                };
                
                return _client.UpdateInventory(serviceUpdate);
            }
            catch (EndpointNotFoundException ex)
            {
                throw new ServiceException("Book service is not available", ex);
            }
            catch (Exception ex)
            {
                throw new ServiceException($"Error updating inventory: {ex.Message}", ex);
            }
        }

        /// <summary>
        /// Converts BookStorage service Book model to local Book model
        /// </summary>
        private Book ConvertToLocalBookModel(BookServiceReference.Book book)
        {
            if (book == null) return null;

            return new Book
            {
                Id = book.Id,
                Title = book.Title ?? "Unknown Title",
                Author = book.Author ?? "Unknown Author",
                ISBN = book.ISBN,
                Category = book.Category,
                PublicationYear = book.PublicationYear,
                Publisher = book.Publisher,
                CopiesAvailable = book.CopiesAvailable,
                Description = book.Description,
                CoverImageUrl = book.CoverImageUrl
            };
        }
    }

    public class ServiceException : Exception
    {
        public ServiceException(string message) : base(message) { }
        public ServiceException(string message, Exception innerException) : base(message, innerException) { }
    }

    /// <summary>
    /// This namespace contains proxy types generated from the service reference
    /// For demonstration purposes, these are defined here
    /// In a real implementation, these would be generated by the service reference
    /// </summary>
    namespace BookServiceReference
    {
        [ServiceContract]
        public interface IBookService
        {
            [OperationContract]
            Book GetBookById(string id);

            [OperationContract]
            bool UpdateInventory(InventoryUpdate update);
        }

        /// <summary>
        /// Book model from the BookStorage service
        /// </summary>
        public class Book
        {
            public string Id { get; set; }
            public string Title { get; set; }
            public string Author { get; set; }
            public string ISBN { get; set; }
            public string Category { get; set; }
            public int PublicationYear { get; set; }
            public string Publisher { get; set; }
            public int CopiesAvailable { get; set; }
            public string Description { get; set; }
            public string CoverImageUrl { get; set; }
        }

        /// <summary>
        /// Inventory update model from the BookStorage service
        /// </summary>
        public class InventoryUpdate
        {
            public string BookId { get; set; }
            public int QuantityChange { get; set; }
        }

        /// <summary>
        /// Client proxy for the BookStorage service
        /// In a real implementation, this would be generated from the service reference
        /// </summary>
        public class BookServiceClient : ClientBase<IBookService>, IBookService
        {
            public BookServiceClient(Binding binding, EndpointAddress address) 
                : base(binding, address)
            {
            }

            public Book GetBookById(string id)
            {
                return Channel.GetBookById(id);
            }

            public bool UpdateInventory(InventoryUpdate update)
            {
                return Channel.UpdateInventory(update);
            }
        }
    }
} 